export const SAVE_INTRINSIFY_CONFIG = "SAVE_INTRINSIFY_CONFIG";
export const DELETE_INTRINSIFY_CONFIG = "DELETE_INTRINSIFY_CONFIG";
export const SET_CURRENT_INTRINSIFY_CONFIG = "SET_CURRENT_INTRINSIFY_CONFIG";
